version: "3"
services:
  app:
    image: mozilla/autograph
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__heartbeat__"]
      interval: 60s
      timeout: 10s
      retries: 3

  edge:
    build:
      context: .
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:8080"
    command:
      [
        "/usr/local/bin/autograph-edge",
        "-u",
        "http://app:8000/",
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__heartbeat__"]
      interval: 60s
      timeout: 10s
      retries: 3

  test:
    build:
      context: ./integration_test
    depends_on:
      edge:
        condition: service_healthy
