name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Restrict tests to the most recent commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run unit tests
        shell: bash
        run: make test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Pull autograph image
        shell: bash
        run: docker pull mozilla/autograph

      - name: Build autograph-edge
        shell: bash
        run: docker compose build

      - name: Sign test APKs and XPIs and verify the APK
        shell: bash
        run: docker compose run test
